apiVersion: v1
kind: Pod
metadata:
  name: test-ed
  labels:
    name: test-ed
spec:
  containers:
  - name: test-container
    image: k8s.gcr.io/test-webserver 
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
      - name: cache-volume
        mountPath: /cache
  volumes:
    - name:  cache-volume
      emptyDir: {}
