apiVersion: apps/v1
kind: deployment
metdata:
  name: redis-slave
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      role: slave
      tier: backend
  template:
    metdata:
      labels:
        app: redis
        role: slave
        tier: backend
    sepc:
      containers:
        - name: slave
          image: gcr.io/google_samples/gb-redisslave:v1
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 6379
